"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# === Alap könyvtár ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Secret key ===
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "dev-secret-ne-hagyd-igy-productionben"
)

# === Debug mód ===
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# === ALLOWED_HOSTS ===
# Renderen az env-ben add meg:
# DJANGO_ALLOWED_HOSTS = vag-projekt.onrender.com,localhost,127.0.0.1
ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")


# ======================================================================
# Alkalmazások
# ======================================================================

INSTALLED_APPS = [
    # alap Django appok
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 3rd party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # saját appok
    "accounts",
]


# ======================================================================
# Middleware
# ======================================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS mindig legelöl
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# ======================================================================
# Adatbázis
# ======================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "vag_forum_db"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "admin"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# ======================================================================
# Jelszó validáció
# ======================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ======================================================================
# Nemzetközi beállítások
# ======================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ======================================================================
# Statikus fájlok
# ======================================================================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======================================================================
# CORS / CSRF – React frontend + Render backend
# ======================================================================

# FRONTEND Render URL-je:
# ha nálad más, ezt írd át pl. "https://frontend-igcv.onrender.com"
FRONTEND_ORIGIN = os.environ.get(
    "FRONTEND_ORIGIN",
    "https://vag-frontend.onrender.com"
)

# BACKEND Render URL-je:
BACKEND_ORIGIN = os.environ.get(
    "BACKEND_ORIGIN",
    "https://vag-projekt.onrender.com"
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # helyi Vite fejlesztő szerver
    FRONTEND_ORIGIN,          # Renderes frontend
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    BACKEND_ORIGIN,           # saját backend Renderen
    FRONTEND_ORIGIN,          # frontend domain is legyen trusted
]

CORS_ALLOW_CREDENTIALS = True


# ======================================================================
# Django REST Framework
# ======================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}


# ======================================================================
# Email – Gmail SMTP
# ======================================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Ha akarod, ezeket is kiviheted env-be:
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "vagteszt@gmail.com")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_HOST_USER = "vagteszt@gmail.com"
EMAIL_HOST_PASSWORD = "jney dzxg kyxo bvau"  # Gmail app jelszó (jobb lenne env-ben)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
